export enum DownloadStatus {
  IDLE = "IDLE",
  IN_QUEUE = "IN_QUEUE",
  PROCESSING = "PROCESSING",
  DOWNLOADING = "DOWNLOADING",
  DOWNLOADED = "DOWNLOADED",
  FAILED = "FAILED",
  CONNECTING_TO_LIBGEN = "CONNECTING_TO_LIBGEN",
  FETCHING_MD5 = "FETCHING_MD5",
}
