export default {
  SEARCH: "? Search",
  NEXT_PAGE: "→ Next Page",
  PREV_PAGE: "← Prev Page",
  EXIT: "✖ Exit",
  SEE_DETAILS: "See Details",
  DOWNLOAD_DIRECTLY: "Download Directly",
  DOWNLOADING: "Downloading...",
  TURN_BACK_TO_THE_LIST: "Turn Back To The List",
  FETCHING_CONFIG: "Fetching configuration file...",
  FINDING_MIRROR: "Finding an available mirror...",
  COULDNT_REACH_TO_MIRROR: "Couldn't reach to mirror",
  GETTING_RESULTS: "Getting results",
  CONNECTION_ERROR: "Connection error",
  TRYING_OTHER_MIRRORS: "Trying other mirrors...",
  ALL_MIRRORS_FAILED: "All mirrors failed. Please try again later.",
  NEXT_PAGE_CHECKING: "→ Next Page",
  NEXT_PAGE_ERROR: "→ Next Page (?) (Retry)",
  NEXT_PAGE_UNAVAILABLE: "→ Next Page (no results on next page)",
  RETRY: "↻ Retry",
  YES: "Yes",
  NO: "No",
};
